---
kind: pipeline
type: docker
name: testing-3.6.7

steps:
  - name: install
    image: python:3.6.7-slim
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  - name: run-test
    image: python:3.6.7-slim
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - pip install --editable .
      - bash test_functionality.sh
---
kind: pipeline
type: docker
name: testing-3.7.1

steps:
  - name: install
    image: python:3.7.1-slim
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  - name: run-test
    image: python:3.7.1-slim
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - pip install --editable .
      - bash test_functionality.sh
---
kind: pipeline
type: docker
name: testing-3.8.0

steps:
  - name: install
    image: python:3.8.0-slim
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  - name: run-test
    image: python:3.8.0-slim
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - pip install --editable .
      - bash test_functionality.sh
